### ISSUE TITLE
WSL-Ubuntu-Install hanging last few days

### ISSUE THREAD

**Issue by andy-kru** [rgryta/PowerShell-WSLTools#9]
Hello, I'm trying to do a fresh installation of Stable-Diffusion-WSL2-Docker and I'm getting an infinity load on WSL-Ubuntu-Install. I assume the launchpad page structure was changed and 'Get all ubuntu versions' step should be aligned.

**Comment by rgryta** [comment]
Possibly. This has happened once before. I'll look into it tomorrow. Thanks for reporting.

**Comment by rgryta** [comment]
@andy-kru - Could you verify that you're using WSLTools version 1.3.3 - check using `Get-InstalledModule WSLTools`

The issue you're describing has indeed happened a few months ago, but was fixed in June. I performed a quick test by running the interactive mode `WSL-Ubuntu-Install -DistroAlias test  -Interactive` and a non-interactive Ubuntu Kinetic installation (`WSL-Ubuntu-Install -DistroAlias test -Version kinetic`). In both cases I did not encounter any issues.

If you're running an older version, please update WSLTools and verify whether it works for you. If it's still failing on version 1.3.3, I'd appreciate if you provided me with a specific command that you're executing and up until which point do you have an output. Thanks again!

**Comment by andy-kru** [comment]
Thank you for the quick response. It worked fine last month, but I got this infinity load issue a few days ago. 
![install bat](https://github.com/rgryta/PowerShell-WSLTools/assets/45319374/28b22241-697b-415c-9273-45d1e6414da9)

I have the latest WSLTools installation:

```powershell
PS C:\Windows\system32> Get-InstalledModule WSLTools

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
1.3.3      WSLTools                            PSGallery            PowerShell WSL focused utility module
``` 

I'm not experienced with PowerShell, but I was trying to add some debug output to `C:\Program Files\WindowsPowerShell\Modules\WSLTools\1.3.3\Public\WSL-Ubuntu-Install.ps1`. I'm getting this endless loop on this piece of code:

```powershell
	# Get all ubuntu versions
	Do {
		$ihtml, $versions = Invoke-WebParseable -Uri https://git.launchpad.net/cloud-images/+oci/ubuntu-base/refs/tags
		if ($ihtml) {
			$prop = "IHTMLAnchorElement_pathname"
			$search = "IHTMLAnchorElement_search"
			$class = "IHTMLElement_className"
			$innerText = "IHTMLElement_innerText"
			$href = "IHTMLAnchorElement_href"
		}
		if (-not $ihtml) {
			$prop = "pathname"
			$search = "search"
			$class = "className"
			$innerText = "innerText"
			$href = "href"
		}
		
		$versions = $versions.getElementsByTagName("a")
		$parsed_versions = $versions | Where-Object {$_.$prop -eq "cloud-images/+oci/ubuntu-base/tag/" -And $_.$search -match  '.*(i386)|(amd64).*'}
		
		$parsed_versions = $parsed_versions | % {Write-Output $($_.$search | Select-String -Pattern 'dist\-\w+\-(i386|amd64)-\d+.*' )} | % { $_.Matches } | % { $_.Value } 
	
	}
	Until ($parsed_versions.Count -gt 0)
``` 
I assume `$parsed_versions` is always empty, but I could not find a root cause. Could you please suggest what I can evaluate here?

**Comment by rgryta** [comment]
Ooooh, I hate it when it does that.

I'm not entirely sure what is happening here, I do know OF this bug though. Sometimes, for some reason, PowerShell simply drops contents of objects that it had stored. It sounds stupid and I have not found any explanation for it, but it happens. Did you perhaps uninstall MS Office lately? Unfortunately some of PowerShell functionalities are very dependant on other packages that Microsoft provides with their other software sets, e.g. IIRC if you have MS Office then ihtml objects should work, but if you don't - they won't. It's more stable if you DO have MS Office.

My best advice would be to use newest PowerShell version (7.6 I believe, although install it from GitHub/winget and not from MS Store) and have installed MS Office.

If you still want to try using your current installation then you can try following case:

```
$response = (Invoke-WebRequest https://git.launchpad.net/cloud-images/+oci/ubuntu-base/refs/tags -UseBasicParsing).Content
$HTML = New-Object -Com "HTMLFile"
try {
	$HTML.IHTMLDocument2_write($response)
	
	$ihtml = $true
	$response = $HTML
}
catch {
	$ihtml = $false
		
	$src = [System.Text.Encoding]::Unicode.GetBytes($response)
	$HTML.write($src)
	$response = $HTML.body
}
```
Verify what's under `$ihtml` and whether `response` contains anything.

If $response is empty, then something's bad. Check the URL within your browser - maybe your network provider blocks it? Idk.

If it's not empty, then let me know when does it drop the object contents.

First set up your environment to use ihtml or not:

```
if ($ihtml) {
			$prop = "IHTMLAnchorElement_pathname"
			$search = "IHTMLAnchorElement_search"
			$class = "IHTMLElement_className"
			$innerText = "IHTMLElement_innerText"
			$href = "IHTMLAnchorElement_href"
}
if (-not $ihtml) {
			$prop = "pathname"
			$search = "search"
			$class = "className"
			$innerText = "innerText"
			$href = "href"
}
```
And then verify where does it break:
```
$versions = $response
$versions = $versions.getElementsByTagName("a")
// Are $versions visible? Check twice - Again, I don't know why, but after checking object's contents sometimes they disappear on the 2nd check...

$parsed_versions = $versions | Where-Object {$_.$prop -eq "cloud-images/+oci/ubuntu-base/tag/" -And $_.$search -match  '.*(i386)|(amd64).*'}
		
$parsed_versions = $parsed_versions | % {Write-Output $($_.$search | Select-String -Pattern 'dist\-\w+\-(i386|amd64)-\d+.*' )} | % { $_.Matches } | % { $_.Value } 
```

At what stage do $parsed_versions disappear?

Unfortunately that's as far as I can help. I'm not a PS expert and from my testing it, it's VERY buggy when it comes to retaining it's objects in memory - I have no idea why people like it :D

I do plan on rewriting all this to a dedicated commandline program at some point, but I don't really have time for it these days.

Either your network seems to be blocking the URL or your PS environment is dropping the object's contents - that's why `-gt` check is there actually. I've never had it loop so hard though.

**Comment by rgryta** [comment]
Also, noted that you're trying to install Stable-Diffusion from my other repo. I've just checked whether it still works and they updated their intialization scripts again, which breaks it - I'll push an update to that repository as well, along with a switch from SD 2.1 to SD XL.

Update: Patched the Stable-Diffusion repo

It's quite late though so I'll be back tomorrow

**Comment by rgryta** [comment]
Another question, if the objects are being dropped between these two lines:

```
$parsed_versions_1 = $versions | Where-Object {$_.$prop -eq "cloud-images/+oci/ubuntu-base/tag/" -And $_.$search -match  '.*(i386)|(amd64).*'}
		
$parsed_versions_2 = $parsed_versions_1 | % {Write-Output $($_.$search | Select-String -Pattern 'dist\-\w+\-(i386|amd64)-\d+.*' )} | % { $_.Matches } | % { $_.Value } 
```
Then please attach text files with the output of the $parsed_versions_1.

**Comment by andy-kru** [comment]
Thanks for the feedback, I could execute it with the latest Powershell 7.3.6. I actually installed Microsoft Office 365 recently (previously, I didn't have it, and everything was working). So, I assume now I'm going through the `$ihtml = true` path and getting issues because of this on the default Powershell 5.1 version. 

```powershell
$versions = $versions.getElementsByTagName("a")
$parsed_versions = $versions | Where-Object {$_.$prop -eq "cloud-images/+oci/ubuntu-base/tag/" -And $_.$search -match  '.*(i386)|(amd64).*'}
``` 

For this piece of code, I'm able to get the list of `$versions` in the output (aligned with the number of links in the response), but 
`$parsed_versions` is always empty. I assume `$prop` and `$search` attributes are not evaluated for me, but I don't know the Powershell command to check this. I have found this command to debug it, but it doesn't return much:

```powershell
Write-Host ($versions | Format-Table -Property * | Out-String)
``` 

![image](https://github.com/rgryta/PowerShell-WSLTools/assets/45319374/5a7b82ae-784e-40bb-abcd-19cf5ac3d3b1)

I can try to debug it more, but I think there is some problem with my setup (Powershell/Office), and it's working fine with the latest Powershell.

**Comment by rgryta** [comment]
> I can try to debug it more, but I think there is some problem with my setup (Powershell/Office), and it's working fine with the latest Powershell.

So just to reiterate, it's working correctly on powershell 7? IIRC there were some bugs with commands that I'm using with powershell<5.6 so that might be it.

I'll install powershell 5.1 and try to reproduce the issue with it. I don't have too much hope for it. If it's working with the newest powershell then I'm glad though.

FYI - WSLTools also provides a command to automatically install different PowerShell versions. Personally I recommend using GitHub source though - MS Store source is broken and hangs when verifying HyperV settings (known issue with DISM, I've been following it for a year now, but it's still there).

**Comment by andy-kru** [comment]
Yeah, it's working with the latest Powershell, thanks for the support! I don't see much sense in writing a workaround for my case as it might be an existing Powershell 5 problem or my setup, so I'm closing this issue.

**Comment by rgryta** [comment]
I'll still take a look at it in some spare time, but I'm glad it works for you now. Thanks for using my tools! 🙏
